Lose functionality
jensj12/MeesGame pull request #132
Opened 2017-01-11 13:21 UTC by jorisBarkema

now shows a victory or defeat screen, depending on if the player won or lost the game.

2017-01-11 22:54 UTC, jensj12 requested changes

2017-01-11 22:54 UTC, jensj12 commented on MeesGame/Gameplay/GameManagement/SpriteSheet.cs
> +
Formatting

2017-01-13 09:14 UTC, jorisBarkema commented
I know I tried to remove that but couldn't commit when only that was changed, I'll just add a comment or something somewhere.

2017-01-14 16:53 UTC, jensj12 approved these changes

2017-01-14 16:54 UTC, merged