Implemented sounds
jensj12/MeesGame pull request #133
Opened 2017-01-11 15:58 UTC by twjvdhorst

Added all sounds. Currently, the theme song keeps playing all the time, can be changed if desired

2017-01-11 23:00 UTC, jensj12 requested changes
Please rebase, diff shows edits from other (already merged) sound branch.

2017-01-11 23:00 UTC, jensj12 commented on MeesGame/Gameplay/GameObjects/TilesTypes/DoorTile.cs
> +                GameEnvironment.AssetManager.PlaySound("open_door");
Do this in the EnterTile function, OpenDoor will be removed.

2017-01-11 23:00 UTC, jensj12 commented on MeesGame/UI/Controls/Button.cs
> +
Formatting

2017-01-11 23:00 UTC, jensj12 commented on MeesGame/Gameplay/GameManagement/AssetManager.cs
> +        snd.Play(soundLevel, 0.0f, 0.0f);
As in the other PR, this change isn't needed.

2017-01-13 13:50 UTC, twjvdhorst commented on MeesGame/UI/Controls/Button.cs
> +
I don't really know what would be wrong with the formatting, but since I didn't work on it (Dennis did), I might not see the problem

2017-01-14 11:16 UTC, jensj12 commented
I can't see the branch locally because the name of the brach is the same as what dennis used for his button sound (it's probably the same branch).

2017-01-14 11:35 UTC, jensj12 approved these changes

2017-01-14 11:36 UTC, merged