Added edges to buttons
jensj12/MeesGame pull request #134
Opened 2017-01-12 22:06 UTC by nessemis

2017-01-12 22:18 UTC, jensj12 commented on MeesGame/UI/Interfaces/IMeasuredDimensions.cs
> +}
Don't remove newlines at file end

2017-01-13 12:01 UTC, nessemis commented
@jensj12  that one slipped through. Fixed now

2017-01-14 11:44 UTC, jensj12 commented
Please provide a description of what you've done. I expected more than just a plain border around every button. Make the border light up instead of using a key overlay when hovering over a button.

2017-01-14 12:36 UTC, LisanneW commented on MeesGame/UI/DefaultUIValues.settings
>  </SettingsFile>
Missing newline

2017-01-14 13:40 UTC, jensj12 requested changes

2017-01-14 13:40 UTC, jensj12 commented on MeesGame/UI/Components/Texture.cs
> +            set { color = value;
Format this as a normal function

2017-01-14 13:40 UTC, jensj12 commented on MeesGame/UI/Components/Texture.cs
> +            get { return texture; }
Put the get before the set, and format set as a normal function

2017-01-17 17:44 UTC, LisanneW requested changes
Invalidate the color picker when moving to a new tile.

2017-01-17 18:14 UTC, nessemis commented
@LisanneW fixed the colorpicker not showing up/being removed.

2017-01-18 10:00 UTC, jensj12 approved these changes

2017-01-18 10:00 UTC, LisanneW approved these changes

2017-01-18 10:02 UTC, merged