Refactor maze generator
jensj12/MeesGame pull request #135
Opened 2017-01-14 15:14 UTC by jensj12

Split class into 3 files, use and object of the class and use directions for deciding the next point

2017-01-14 15:26 UTC, LisanneW commented on MeesGame/Gameplay/Generator/MazeGeneratorInit.cs
> +            // Make sure the dimensions of the maze are add and reasonable.
"odd and reasonable" I presume

2017-01-14 15:39 UTC, LisanneW commented on MeesGame/Gameplay/Generator/MazeGeneratorMain.cs
> +using System.Collections.Generic;
Unnecessary usings.

2017-01-14 15:40 UTC, LisanneW commented on MeesGame/Gameplay/Generator/MazeGeneratorMain.cs
> +}
Missing newline.

2017-01-14 16:47 UTC, maxmeijer42 requested changes

2017-01-14 16:47 UTC, maxmeijer42 commented on MeesGame/Gameplay/Generator/MazeGeneratorInit.cs
> +            int numKeys = 0;
This should be a member variable like the others

2017-01-14 16:47 UTC, maxmeijer42 commented on MeesGame/Gameplay/Generator/MazeGeneratorInit.cs
> +        private void InitMazeGen(int numRows, int numCols, int difficulty)
You could split this into some helper methods.

```c#
useDifficulty(difficulty);
makeSureDimensionsAreValid();
createTileFieldWithJustWalls();
initNodesToDo();
initKeyNodes();
initExitScores();
```

2017-01-14 16:47 UTC, maxmeijer42 commented on MeesGame/Gameplay/Generator/MazeGeneratorMain.cs
> +                // Continue from the last node, or take a random one
You could make this a helper function:

    Point current = determineNextNode();

And then later you can do

    nodesToDo.RemoveAt(nodesToDo.count-1);

2017-01-14 16:47 UTC, maxmeijer42 commented on MeesGame/Gameplay/Generator/MazeGeneratorMain.cs
> +                // Make an arrray and fill it with 1-4 in a random order.
Comment does not match function name

2017-01-14 16:47 UTC, maxmeijer42 commented on MeesGame/Gameplay/Generator/MazeGeneratorMain.cs
> +                                if (randNumb < loopHoleChance * BIGINT) tileToAdd = new HoleTile();
I found it hard to see what was going on at a first glance. Do you think this is clearer?

```c#
if (randNumb < loopHoleChance * BIGINT) tileToAdd = new HoleTile();
else if (randNumb < (loopDoorChance + loopHoleChance) * BIGINT) tileToAdd = new DoorTile();
else tileToAdd = new FloorTile();

2017-01-15 16:36 UTC, jensj12 commented on MeesGame/Gameplay/Generator/MazeGeneratorMain.cs
> +                // Continue from the last node, or take a random one
Using ```nodesToDo.RemoveAt(nodesToDo.count-1);``` At the end will cause newly added tiles to be removed from the list.

2017-01-15 16:37 UTC, jensj12 commented on MeesGame/Gameplay/Generator/MazeGeneratorMain.cs
> +                                if (randNumb < loopHoleChance * BIGINT) tileToAdd = new HoleTile();
I've done something similar in a helper function, and fixed a calculation bug with it.

2017-01-15 17:02 UTC, maxmeijer42 approved these changes
Nice, code is much cleaner now :)

2017-01-15 17:03 UTC, merged