Added Climbing Sound
jensj12/MeesGame pull request #189
Opened 2017-01-24 16:23 UTC by twjvdhorst

2017-01-24 21:31 UTC, jorisBarkema submitted a review, later dismissed
It sounds good though.

2017-01-24 21:31 UTC, jorisBarkema commented on MeesGame/Gameplay/Content/Content.mgcb
> -
Try to avoid changing whitelines, I'm not sure but it could cause conflicts if someone else wants to change anything with content later.

2017-01-24 21:31 UTC, jorisBarkema commented on MeesGame/MeesGame.csproj
> +      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
Don't think this line should be here as it isn't there for any of the other files, if it's intentional and for a good reason let me know though.

2017-01-24 21:48 UTC, jorisBarkema commented
Still whiteline changes in content.mgcb, and one line </content> in csproj file, but I guess if that doesn;t cause any errors that's fine.

2017-01-24 22:00 UTC, jensj12 requested changes
The sound will also play if an AI dummy uses a portal. The tags in csproj can be self-closing to keep it consistent with the rest of the file.

2017-01-24 22:43 UTC, LisanneW commented on MeesGame/Gameplay/Content/Content.mgcb
> -
Content automatically deletes these whitelines so I think its better if they are gone, they shouldn't even have been there in the first place.

2017-01-25 07:10 UTC, jensj12 commented
icon.png should have been removed

2017-01-26 12:08 UTC, jensj12 approved these changes

2017-01-26 23:04 UTC, merged

2017-01-26 23:32 UTC, jensj12 commented
csproj is a generated file. It will automatically remove the newline at the end of the file next time it is edited. @maxmeijer42