Graphics resize fix
jensj12/MeesGame pull request #207
Opened 2017-01-30 22:31 UTC by nessemis

Graphics can now properly resize. Also looks better because rendering now happens on a per-pixel basis.

Known issues: UI doesn't update until the mouse hovers over one of it's elements. This will be fixed in a separate pull request (because the underlying issue isn't related to resizing).

2017-01-30 22:32 UTC, nessemis commented on MeesGame/Gameplay/GameManagement/GameEnvironment.cs
> +    protected Point preferedWindowSize;
I've renamed WindowSize to PreferedWindowSize because the window size isn't necessarily equal to this variable.

2017-01-31 12:02 UTC, jensj12 commented
The two PR's depend on each other, splitting them only makes merging harder.

2017-01-31 12:08 UTC, jensj12 commented
I don't like the fullscreen main menu, buttons are not properly centered in the bottom bar.

2017-01-31 12:08 UTC, nessemis commented
@jensj12 The two pull request solve completely separate issues (even though some issues are more apparant in this branch. I will change the positioning of the buttons right away though

2017-01-31 12:12 UTC, nessemis commented
@jensj12 The buttons are now organized left, center, right.

2017-01-31 13:22 UTC, jensj12 commented
I've asked @twjvdhorst to move the level editor button back to the main menu (and edit the strings so it fits). This works, but conflicts with that.
Another issue, the default screen size is much bigger than it used to be and already feels like fullscreen to me. Quitting fullscreen reposistions the window in the top-left corner of the game.

2017-01-31 15:45 UTC, maxmeijer42 requested changes

2017-01-31 15:45 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameManagement/GameEnvironment.cs
> +    protected Point preferedWindowSize;
It's preferred not prefered

2017-01-31 15:45 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameManagement/GameEnvironment.cs
> +    public Point PreferedWindowSize
Spelling

2017-01-31 16:15 UTC, jensj12 commented
Please fix all conflicts ASAP. This branch fixes some issues introduced in #208.

2017-01-31 17:53 UTC, nessemis commented
@jensj12  fixed

2017-01-31 18:12 UTC, jensj12 commented
Please do your merges properly. I don't like seeing changes from other branches.

2017-01-31 19:00 UTC, jensj12 requested changes
The level editor button is gone.

2017-01-31 21:23 UTC, nessemis commented
@jensj12  @maxmeijer42 I've fixed both issues. I don't know what went wrong with merging, but I fixed it by hand-picking the needed changes. (the scrollbars should be fixed now as well, somehow got into the wrong branch).

2017-01-31 21:57 UTC, maxmeijer42 commented
@nessemis No, it's not fixed

2017-01-31 22:30 UTC, jensj12 commented
What is going on here? It seems the changes have been moved to a new branch 'new_resize_fix' and this branch is left with only the extra buttons fix. @nessemis don't mess up now, we need this change.

2017-01-31 23:20 UTC, closed without merging