Dennisbranche
jensj12/MeesGame pull request #22
Opened 2016-11-24 21:16 UTC by nessemis

Added a ui for the titlescreen, and made a folder explorer for level loading. Level loading in itself is not yet implemented because I don't have the interface to send it to the playingstate (but can in theory easily send a string with the filename). I have placed all the strings that I used in a resource file called Strings and placed it in the root directory. Created a default spritefont in the Contens class (THIS MIGHT CAUSE A MERGE CONFLICT).

2016-11-24 22:30 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/Button.cs
> +        protected Texture2D HoverBackground;
met een kleine letter als het kan

2016-11-24 22:30 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/Button.cs
> +namespace MeesGame.Gameplay.UIObjects
namespace MeesGame

2016-11-24 22:30 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/Button.cs
> +                    OnClickEventLauncher();
Je kunt events aanroepen met null check in C#: OnClick?.Invoke()

2016-11-24 22:30 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/FileExplorer.cs
> +        //we store the current state of the folder so that we do not have to redraw it every single time;
Volgens mij hoort deze comment bij een andere variabele

2016-11-24 22:49 UTC, maxmeijer42 requested changes
Ziet er goed uit, en werkt. Klassestructuur is duidelijk. We hebben tot nu toe alles in één namespace. We kunnen er ook voor kiezen om verschillende namespaces te maken maar dan moeten we consequent zijn. Hou het nu maar op namespace MeesGame. Verder waren er ook nog een paar andere kleine dingetjes (zie comments)

2016-11-24 22:49 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/ListButton.cs
> +        public bool selected = false;
We hebben afgesproken dit met properties te doen.
Dus:

```c#
protected bool selected = false;
public bool Selected{
  get{return selected;}
  set{selected=value;}
}
```

2016-11-24 22:49 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/FileExplorer.cs
> +        public delegate void ChoseFile(String path, bool succes);
Deze wordt nergens gebruikt of wel?

2016-11-24 22:49 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/TextureGenerator.cs
> +            tmpSpriteBatch.GraphicsDevice.Clear(Color.Wheat);
arbritaire constanten graag als constante in de klasse of als resource

2016-11-24 23:01 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameStates/TitleMenuState.cs
> +                throw new NotImplementedException();
Does not get the job done. PLEASE FIX!!

2016-11-24 23:43 UTC, nessemis commented
Ik heb alles aangepast, en nog een paar andere constanten bovenaan gezet en properties gebruikt ipv een paar public variables. Ik heb deze vervolgens gepushed naar de dennisbranche zodat de veranderingen in de pull request erbij zijn gekomen.

Moet ik verder nog iets doen om aan te geven dat de veranderingen gedaan zijn?

2016-11-25 15:27 UTC, maxmeijer42 commented
Je moet nog pushen want ik zie geen nieuwe commits op je branch

2016-11-25 15:48 UTC, nessemis commented
Bij mij was hij ook verdwenen. Heb de commit teruggehaald met gith shell,
en opnieuw gepushed. Nu staat er op github dat de commit 16 uur geleden is
gedaan 🤔...

On Fri, Nov 25, 2016 at 4:27 PM, Max Meijer <notifications@github.com>
wrote:

> Je moet nog pushen want ik zie geen nieuwe commits op je branch
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jensj12/MeesGame/pull/22#issuecomment-262979095>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGJ6uL538lhrOieldg3dhJO1hmLWyxGqks5rBv5MgaJpZM4K79wl>
> .
>

2016-11-25 16:19 UTC, maxmeijer42 approved these changes

2016-11-25 16:22 UTC, merged

2016-11-25 16:23 UTC, maxmeijer42 commented
@nessemis Kun je volgende keer in je branchnaam beschrijven wat voor veranderingen er in de branch staan?

2016-11-25 16:38 UTC, nessemis commented
doe ik. dacht toen ik de dennisbranche maakte dat branches gebruikt waren
door een persoon ofzo.

On Fri, Nov 25, 2016 at 5:23 PM, Max Meijer <notifications@github.com>
wrote:

> @nessemis <https://github.com/nessemis> Kun je volgende keer in je
> branchnaam beschrijven wat voor veranderingen er in de branch staan?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jensj12/MeesGame/pull/22#issuecomment-262991026>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGJ6uKgppPpM_1AWPPbyf-jlD3kPKVpiks5rBwuZgaJpZM4K79wl>
> .
>