Player movement
jensj12/MeesGame pull request #24
Opened 2016-11-25 17:35 UTC by maxmeijer42

The player can move using WASD keys.

2016-11-25 20:10 UTC, jensj12 requested changes

2016-11-25 20:10 UTC, jensj12 commented on MeesGame/Gameplay/Level/Level.cs
> +        protected TimeSpan timeBetweenActions = new TimeSpan(0,0,0,0,200);//200 ms
Should be TimeSpan.FromMiliseconds(200). Makes comment obsolete.

2016-11-28 22:30 UTC, maxmeijer42 commented
Ik heb extra wijzigingen gecommit

2016-11-29 15:05 UTC, jensj12 approved these changes

2016-11-29 15:05 UTC, merged