Refactor Player and Tile class and add some useful functions and props
jensj12/MeesGame pull request #44
Opened 2016-12-05 18:58 UTC by maxmeijer42

2016-12-06 10:58 UTC, maxmeijer42 commented on MeesGame/Gameplay/Level/Level.cs
> +                    tile.Location = new Point(x, y);
Dit gebeurt al in de TileField klasse. Ik zal het aanpassen

2016-12-07 12:59 UTC, jensj12 approved these changes

2016-12-07 13:02 UTC, jensj12 submitted a review, later dismissed
Contains TODO's, breaks doors (which already crashed anyways, but this reduces functionality even further)

2016-12-07 16:49 UTC, maxmeijer42 commented
The TODO's were already there. I added none. The TODO's were added in PR #43. Doors already crash but storing player history is not the way to check if a player has picked up a key. Code breaks nothing, adds Inventory which can store keys. @LisanneW might want to use that to store Keys.

2016-12-12 13:16 UTC, LisanneW requested changes
Please format files using ctrl+k+d, at least level.cs needs it.

2016-12-12 16:44 UTC, maxmeijer42 commented
Indeed there was a trailing tab in level.cs. It's fixed now.

2016-12-12 17:06 UTC, jensj12 approved these changes

2016-12-12 17:09 UTC, LisanneW approved these changes

2016-12-12 20:08 UTC, merged