wallfixes and new player sprites
jensj12/MeesGame pull request #53
Opened 2016-12-07 16:48 UTC by jorisBarkema

Shadows should be consistent now, added sprites for the player walking other directions,
the vertical little gaps in the walls are probably not related to the sprites, as I noticed they always happen on the whole column, not just between two sprites

2016-12-07 17:04 UTC, maxmeijer42 commented
[Some walls have more shadow than others it seems.](http://puu.sh/sHnOT/55528d0665.png)

I like the new Player sprites btw.

2016-12-07 22:07 UTC, jorisBarkema commented
I'm just going to redo all the shadows friday or saturday morning, it's become quite a mess with different fixes on different tiles...

2016-12-12 13:06 UTC, LisanneW requested changes
The shadows of the single-tile wall block don't look right. Other than that, much better!

2016-12-13 15:46 UTC, LisanneW approved these changes

2016-12-13 15:48 UTC, merged