Level Editor added
jensj12/MeesGame pull request #54
Opened 2016-12-09 15:31 UTC by nessemis

simple level editor which can place tiles of all tiles aviable in the the TileTypes enum on a level.

2016-12-09 19:22 UTC, jensj12 requested changes
Still need to check if there are better ways to handle object references, level now contains two references to the camera

2016-12-09 19:22 UTC, jensj12 commented on MeesGame/Gameplay/GameManagement/SpriteSheet.cs
> +        if(sprite == null)
Please revert this change, this is garbage code

2016-12-09 19:22 UTC, jensj12 commented on MeesGame/Gameplay/GameObjects/Player.cs
> +            //movements are
Are special actions meant to be allowed?

2016-12-09 20:21 UTC, nessemis commented
Removed the garbage code and special actions aren't allowed for the editorplayer anymore

2016-12-12 16:52 UTC, maxmeijer42 commented
What was changed in the walls image? I can't see the difference.

2016-12-13 14:47 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameManagement/SpriteSheet.cs
> +    /// <param name="origin">locaiton the sprite should consider its reference point for drawing and rotating</param>
Maybe you can download a spellchecker for visual studio comments. Also, capital letters exist.

2016-12-13 14:47 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameStates/LevelEditorState.cs
> +        /// fills the list of thiles
Errors like this might be avoided with a spell checker

2016-12-14 12:19 UTC, jensj12 commented on MeesGame/Gameplay/Level/Level.cs
> +namespace MeesGame.Gameplay.Level
Namespace

2016-12-14 12:22 UTC, jensj12 approved these changes

2016-12-14 12:24 UTC, merged