Qlearning2
jensj12/MeesGame pull request #61
Opened 2016-12-14 12:39 UTC by 4144805

2016-12-14 12:52 UTC, jensj12 requested changes

2016-12-14 12:52 UTC, jensj12 commented on MeesGame/Gameplay/Level/Level.cs
> +        public TimeSpan timeBetweenActions = TimeSpan.FromMilliseconds(300);
Create property instead

2016-12-14 12:52 UTC, jensj12 commented on MeesGame/Gameplay/GameObjects/Player.cs
> +            this.position = tileField.GetAnchorPosition(location);
Code duplication, already done in Player class

2016-12-15 18:25 UTC, maxmeijer42 commented on MeesGame/AI/QLearning.cs
> +    /// Deze class bevat alle informatie over het level die de qLearning AI nodig heeft om te leren.
English please

2016-12-15 18:25 UTC, maxmeijer42 commented on MeesGame/AI/QLearning.cs
>          private double learningRate, discountFactor;
If you split these variables onto multiple lines you can split the documentation between them

2016-12-15 18:25 UTC, maxmeijer42 commented on MeesGame/AI/QLearning.cs
> +        public int numberOfKeys()
Method names should always start with a verb. Either make this a property or change the name. Also, the naming convention is to use capital letters..

2016-12-15 18:25 UTC, maxmeijer42 commented on MeesGame/AI/QLearning.cs
> +        //waarom performt deze methode de action al als er een methode AITrainingPerformAction is? Omdat dit níét voor de trainingmodus is maar voor de echte modus.
Discussies niet houden in comments in de code

2017-01-24 09:40 UTC, jensj12 commented
PR contains changes from threaded-AI branch

2017-02-01 06:50 UTC, closed without merging