Bnijmeijer fileio 1 5
jensj12/MeesGame pull request #64
Opened 2016-12-14 13:25 UTC by BNijmeijer

2016-12-14 15:37 UTC, jensj12 commented on MeesGame/Gameplay/GameManagement/GameObject.cs
> +    public int layer;
Is it still needed to make everything public?

2016-12-15 17:34 UTC, maxmeijer42 reviewed
Haven't tested it yet, but it looks good.

2016-12-15 17:34 UTC, maxmeijer42 commented on MeesGame/Gameplay/Level/FileIO.cs
> +        /// <param name="filename"> The name of the file the level is being saved to. </param>
Parameter does not exist

2016-12-15 17:34 UTC, maxmeijer42 commented on MeesGame/Gameplay/Level/FileIO.cs
>                  Stream stream = new FileStream(fileName, FileMode.Create);
Catch exceptions

2016-12-15 17:34 UTC, maxmeijer42 commented on MeesGame/Gameplay/Level/Level.cs
>          public void WriteXml(XmlWriter writer)
This class is never serialized I believe, so it does not need to implement IXmlSerializable

2016-12-16 16:06 UTC, jensj12 requested changes

2016-12-16 16:06 UTC, jensj12 commented on MeesGame/MeesGame.csproj
> +    <Compile Include="Gameplay\Level\FileIO.cs" />
FileIO.cs is already in the list. This generates an error.

2016-12-19 11:45 UTC, BNijmeijer commented
I've overhauled the FileIO.Save and FileIO.Load methods, because the way I was trying to serialize everything was becoming a huge mess. Now, everything you'd need to create a level is contained in the LevelData class, and as such, both methods use this class in order to (de-)compose levels.

2016-12-21 12:25 UTC, BNijmeijer commented on MeesGame/Gameplay/Level/FileIO.cs
> +        /// <param name="filename"> The name of the file the level is being saved to. </param>
Fixed

2016-12-21 12:25 UTC, BNijmeijer commented on MeesGame/Gameplay/Level/FileIO.cs
>                  Stream stream = new FileStream(fileName, FileMode.Create);
Fixed

2016-12-25 22:55 UTC, jensj12 commented
Merged via #87.

2016-12-25 22:55 UTC, closed without merging