PlayingstateUI (heet nu UI ipv GUI)
jensj12/MeesGame pull request #72
Opened 2016-12-15 16:33 UTC by nessemis

2016-12-15 17:24 UTC, maxmeijer42 requested changes
There are some naming, documentation and convention issues.

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameManagement/GameEnvironment.cs
> +    protected static GameEnvironment gameEnvirontment;
The word is Environment, without a T. ctrl+R ctrl + R

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameManagement/GameEnvironment.cs
> +    public static GameEnvironment GetGameEnvironment
The property should be called GameEnvironment

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameObjects/PlayerState.cs
> +        public delegate void InventoryChangedEventHandler();
Unused

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameObjects/PlayerState.cs
> +        private void InventoryChanged()
Please remove this function, it has too little functionality

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameStates/LoadMenuState.cs
> +        private UIContainer UIContainer;
should be uiContainer

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameStates/LoadMenuState.cs
> +        public LoadMenuState()
Much better

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/UIObject.cs
> +        /// draws the UIel
Not helpful

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/UIObject.cs
> +                if (parent != null)
This condition should be 
    if(parent!=null && value)

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/UIObject.cs
> +        public virtual bool Invalidate
Please make this a function Invalidate(). If it is not a function it should not be a verb, it should be Invalidated.
Also, add documentation to this property.

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/UIObject.cs
> +            set { visible = value;
Please add a newline here

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/UIObject.cs
> +        public virtual bool Invalidate
Please make this a function Invalidate(). If it is not a function it should not be a verb, it should be Invalidated.
Also, add documentation to this property.

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/UIObject.cs
> +            if (Invalidate == true)
if (Invalidated)

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/UIObject.cs
>          /// location = relative location to the parent of the object
Please use the default format for documentation

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/ScrollBar.cs
>          //The scroll distance before we began dragging. This variable is needed because otherwise we'd have
Please use documention tags

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/Objects/Button.cs
> +                base.Invalidate = true;
What is this????? Are you sure Invalidate = false should set Invalidate to true?

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/Objects/Button.cs
>          /// Method used to create a customizable button
You can reword this: Creates a customizable button

2016-12-15 17:24 UTC, maxmeijer42 commented on MeesGame/Gameplay/UIObjects/Objects/Button.cs
>          /// Text = the text the button displays
Use the docs format

2016-12-15 19:50 UTC, jensj12 commented on MeesGame/Gameplay/GameManagement/GameEnvironment.cs
> +    public static GameEnvironment GetGameEnvironment
GameEnvironment generates an error, if you have better suggestions, please let us know.

2016-12-16 15:51 UTC, jensj12 commented
Remember to not put multiple things in one PR. This contains both an in-game overlay and extensions to the level editor. It is much easier to merge smaller PR's.

2016-12-20 13:53 UTC, maxmeijer42 commented on MeesGame/Gameplay/GameManagement/GameEnvironment.cs
> +    public static GameEnvironment GetGameEnvironment
The normal way to handle singletons is to call it Instance. Then you can use GameEnvironment.Instance. So I suggest renaming it to Instance

2016-12-20 20:55 UTC, nessemis commented
@maxmeijer42 New commits that have adressed the requested changes (except the one of Jens, because I couldn't undo all the changes)

2016-12-20 21:02 UTC, maxmeijer42 approved these changes
Going to approve this now, we'll refactor later.

2016-12-20 21:05 UTC, merged