Fog of war
jensj12/MeesGame pull request #75
Opened 2016-12-16 13:39 UTC by jorisBarkema

added fog of war

2016-12-16 14:18 UTC, jensj12 requested changes
Since the fogOfWar bool should be able to override the visibility settings of the tile, I prefer a new bool for the tile. That also makes it possible to toggle fog of war in-game. Override the draw function, check that bool and call the base function. The draw function will be overridden anyways because some tiles need a secondary sprite.
Anyways, I love it.

2016-12-16 18:08 UTC, jorisBarkema commented
Tiles now has a fogOfWar and a visited bool, the visited bool is necessary for togglability. Tiles also has a toggleFogOfWar method, to toggle the fog of war just call the toggleFogOfWar method for each tile. Did not add a method for that anywhere yet as the toggling will go through the UI and I don't know exactly how that's going to interact, so where that method should be.

2016-12-16 18:11 UTC, jorisBarkema commented
so the bug was...I set visible to false when the tile was visited.....

2016-12-17 10:17 UTC, jorisBarkema commented
I think this is what you were talking about.

2016-12-17 11:30 UTC, jensj12 requested changes

2016-12-17 11:30 UTC, jensj12 commented on MeesGame/Gameplay/GameObjects/Tile.cs
> +        protected Tile(bool fogOfWar = true, string assetName = "", TileType tileType = TileType.Floor, int layer = 0, string id = "") : base(assetName, layer, id)
Don't add this parameter to the constructor (same for all tile subclasses).

2016-12-17 11:40 UTC, jorisBarkema commented
forgot about those, fixed now

2016-12-17 12:55 UTC, jensj12 requested changes

2016-12-17 12:55 UTC, jensj12 commented on MeesGame/Gameplay/GameObjects/TileField.cs
> +        public TileField(int rows, int columns, int layer = 0, bool fogOfWar = true, string id = "") : base(rows, columns, layer, id)
Place fogOfWar before layer

2016-12-17 12:55 UTC, jensj12 commented on MeesGame/Gameplay/GameObjects/Tile.cs
> +                sprite.Draw(spriteBatch, this.GlobalPosition, origin);
Call base.Draw and don't check for sprite!=null

2016-12-17 12:55 UTC, jensj12 commented on MeesGame/Gameplay/GameObjects/DoorTile.cs
> +        public DoorTile(bool fogOfWar = true, int layer = 0, string id = "") : base(fogOfWar, "horizontalDoorOverlay", TileType.Door, layer, id)
Remove fogOfWar

2016-12-17 12:55 UTC, jensj12 commented on MeesGame/Gameplay/GameObjects/DoorTile.cs
> +        public KeyTile(bool fogOfWar = true, int layer = 0, string id = "") : base(fogOfWar, "keyOverlay", TileType.Key, layer, id)
Remove fogOfWar

2016-12-17 15:20 UTC, jensj12 approved these changes

2016-12-17 15:23 UTC, merged